#!/usr/bin/env bash

#!
#! Prints a given text inside a colored box.
#!

readonly color=${1:?missing required argument <color>}
readonly text=${2:-$(cat /dev/stdin)}
readonly width=116
readonly margin_left=2
readonly margin_right=2
readonly total_width=$(( width + margin_left + margin_right ))

printf "\n%b%${total_width}s%b\n" "${color}" ' ' "${RESET_COLORS}"

while IFS= read -r line; do
    printf "%b%${margin_left}s%-${width}s%${margin_right}s%b\n" "${color}" ' ' "${line}" ' ' "${RESET_COLORS}"
done <<< "$(fold --spaces --width=${width} <<< "${text}")"

printf "%b%${total_width}s%b\n" "${color}" ' ' "${RESET_COLORS}\n"
