#!/usr/bin/env bash

#!
#! Executes a given Docker image without any networking capabilities, ensuring
#! that it cannot communicate with the outside world in any way. This ensures
#! that you can run e.g. linting software without worrying about it going over
#! all your source code as it is impossible for the program to tell anyone
#! about what it parsed.
#!

exec docker run \
    --network none \
    --rm \
    --volume "$(pwd):/usr/local/src" \
    --workdir /usr/local/src \
    "$@"
