#!/usr/bin/env bash

#!
#! Use this to run make in case you have problems figuring out what the heck is
#! going on. Use it with the same arguments as you would invoke make normally.
#!
#! Be warned, the output is extremely verbose.
#!

DEBUG=1 exec make --debug=all --trace --print-directory "$@"
