#!/usr/bin/env bash

readonly cmd=${1:?missing required argument <command>}

if ! command-exists "${cmd}"; then
    continue-with() {
        printf '%b%s%b is missing from your system. Should I try installing it via %b%s%b? [yN] ' \
            "${FG_CYAN}" "${cmd}" "${RESET_COLORS}" \
            "${FG_CYAN}" "$1" "${RESET_COLORS}"

        read -r answer
        case "${answer}" in
            [Yy]*) return ;;
            *) exit "${EX_UNAVAILABLE}" ;;
        esac
    }

    if command-exists brew; then
        continue-with brew
        (unset BASH_ENV; brew install "${cmd}")
    elif command-exists apt-get; then
        continue-with apt-get
        apt-get install "${cmd}"
    else
        box-err "${cmd} could not be found in your PATH, make sure it is available."
        exit "${EX_UNAVAILABLE}"
    fi
fi
